include:
  - project: 'liipops/django-hoster'
    file: django-hosting.yml
    ref: main

variables:
  DJANGO_SETTINGS_MODULE: defivelo.settings.base
  GUNICORN_APP_NAME: defivelo.wsgi
  LIIP_DOCKER_PYTHON_VERSION: "3.7"
  BASE_ADDITIONAL_APKS: sassc
  HTTPD_RUN_COMPRESS: "true"

stages:
  - test
  - build

test:
  stage: test
  tags:
    - docker-nonswiss-ok
  image: &test_image 'python:3.7.4-buster'
  services:
    - name: postgres:11.8
      alias: db
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    DJANGO_SETTINGS_MODULE: defivelo.settings.test
    DATABASE_URL: postgresql://postgres:postgres@db/postgres
    POSTGRES_PASSWORD: postgres
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    key: *test_image
    paths:
      - .cache/pip
  script:
    - pip install -r requirements/test.txt
    - |
      bash -c "
        echo -n 'Wait until the PostgreSQL server is ready .'
        while ! (echo > /dev/tcp/db/5432) >/dev/null 2>&1; do
          echo -n '.'
          sleep 1
        done
        echo ' Ready!'
      "
    - ./scripts/run_tests.sh

