language: python
addons:
  postgresql: "11"
before_script:
  - psql -c 'create database defivelotest;' -U postgres
install:
  - pip install tox 
script:
  - tox
env:
  - TOXENV=py37-coverage
  - TOXENV=flake8
