language: python
python:
  - "3.7" # Current prod
  - "3.8"
services:
  - postgresql
before_script:
  - psql -c 'create database test_defivelo;' -U postgres
install:
  - pip install tox
script:
  - tox
env:
  - TOXENV=python
