language: python
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database defivelotest;' -U postgres
install:
  - pip install tox 
script:
  - tox
env:
  - TOXENV=py34-coverage
  - TOXENV=py27
  - TOXENV=flake8
