# ================================
#
# Make a copy of this file and name it `docker-compose.override.yml`, then
# choose one among the following configurations and uncomment the lines.
# Finally cross your fingers and run `INITIAL=1 docker-compose up`.

# MINIMAL CONFIGURATION
# ~~~~~~~~~~~~~~~~~~~~~
#
# Visit http://localhost:8000/ to access the Django dev server and
# http://localhost:3000/ to access the Webpack dev server.
#
# version: '3.4'
# services:
#   backend:
#     ports:
#       - 127.0.0.1:8000:8000
#
# PONTSUN CONFIGURATION
# ~~~~~~~~~~~~~~~~~~~~~
#
# Set up pontsun (https://github.com/liip/pontsun) and start it. Then visit
# https://defivelo.docker.test/ to access the Webpack dev server.
#
# version: '3.4'
# x-environment:
#   &x-environment
#   ALLOWED_HOSTS: >-
#     defivelo.docker.test
# x-build-args: &x-build-args
#  # USER_ID: 1001  # Set if your dev user  is non-1000
#  # GROUP_ID: 1001 # Set if your dev group is non-1000
# services:
#  backend:
#    environment:
#      <<: *x-environment
#      SSH_AUTH_SOCK: /.ssh-agent/proxy-socket
#     build:
#       args:
#         <<: *x-build-args
#    volumes:
#      - pontsun_sshagent_socket_dir:/.ssh-agent
#    networks:
#      - default
#      - pontsun
#    labels:
#      - 'traefik.enable=true'
#      - 'traefik.docker.network=pontsun'
#      - 'traefik.backend=defivelo'
#      - 'traefik.port=8000'
#      - 'traefik.frontend.rule=Host:defivelo.docker.test'
# networks:
#   pontsun:
#     external:
#       name: pontsun
