# Generated by Django 2.2.12 on 2020-05-14 13:59

from django.conf import settings
from django.db import migrations, models
from rolepermissions.roles import assign_role
import django.db.models.deletion
from django.contrib.auth import get_user_model

def migrate_organization(apps, schema_editor):
    Organization = apps.get_model("orga", "Organization")
    User = get_user_model()
    EmailAddress = apps.get_model("account", "EmailAddress")
    UserProfile = apps.get_model('user', 'UserProfile')
    Address = apps.get_model('common', 'Address')

    for orga in Organization.objects.all():
        coordinator_names = orga.coordinator_fullname.split(" ")
        user, create = User.objects.get_or_create(
            email=orga.coordinator_email,
            is_active=True,
            defaults={
                "first_name": coordinator_names[0] if len(coordinator_names) > 0 else "",
                "last_name": " ".join(coordinator_names[1:]) if len(coordinator_names) > 1 else "",
            }
        )
        if create:
            address_ptr = Address.objects.create()
            up = UserProfile.objects.create(
                user_id=user.id,
                natel=orga.coordinator_natel,
                status=10,  # USERSTATUS_ACTIVE
                address_ptr_id=address_ptr.id

            )
            email_address, _ = EmailAddress.objects.get_or_create(
                email=user.email,
                defaults={
                    "user_id": user.id
                }
            )
            email_address.user_id = user.id
            email_address.verified = True
            email_address.primary = True
            email_address.save()

        user.is_active = True
        user.save()
        orga.coordinator_id = user.id
        orga.save()
        assign_role(user, "coordinator")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orga', '0006_auto_20170831_1201'),
        ('user', '0055_data_remove_email_from_deleted_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Coordinateur'),
        ),
        migrations.RunPython(migrate_organization),
    ]
