# Generated by Django 2.2.9 on 2020-03-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0055_annualstatesetting_historicalannualstatesetting'),
        ('invoices', '0002_auto_20200304_1525'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoiceline',
            unique_together={('session', 'invoice')},
        ),
    ]
