# Generated by Django 2.2.9 on 2020-03-05 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20200305_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='orga.Organization', verbose_name='Établissement'),
        ),
    ]
