# Generated by Django 1.11.4 on 2017-08-14 13:52
from __future__ import unicode_literals

from django.db import migrations
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_add_user_can_resend_creds_to_power_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='iban',
            field=localflavor.generic.models.IBANField(blank=True, include_countries=('AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GI', 'GR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK', 'SM'), max_length=34, use_nordea_extensions=False),
        ),
    ]
