# Generated by Django 1.11.4 on 2017-08-24 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_auto_20170824_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagedstate',
            name='canton',
            field=models.CharField(choices=[('AR', 'Appenzell Ausserrhoden'), ('BS', 'Basel-Stadt'), ('BE', 'Berne'), ('FR', 'Fribourg'), ('GE', 'Geneva'), ('JU', 'Jura'), ('LU', 'Lucerne'), ('NE', 'Neuchatel'), ('SG', 'St. Gallen'), ('VS', 'Valais'), ('VD', 'Vaud'), ('ZH', 'Zurich'), ('VS-OW', 'Haut-Valais')], max_length=5, verbose_name='Canton'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activity_cantons',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AR', 'Appenzell Ausserrhoden'), ('BS', 'Basel-Stadt'), ('BE', 'Berne'), ('FR', 'Fribourg'), ('GE', 'Geneva'), ('JU', 'Jura'), ('LU', 'Lucerne'), ('NE', 'Neuchatel'), ('SG', 'St. Gallen'), ('VS', 'Valais'), ('VD', 'Vaud'), ('ZH', 'Zurich'), ('VS-OW', 'Haut-Valais')], max_length=41, verbose_name='Défi Vélo mobile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='affiliation_canton',
            field=models.CharField(blank=True, choices=[('', '---------'), ('AR', 'Appenzell Ausserrhoden'), ('BS', 'Basel-Stadt'), ('BE', 'Berne'), ('FR', 'Fribourg'), ('GE', 'Geneva'), ('JU', 'Jura'), ('LU', 'Lucerne'), ('NE', 'Neuchatel'), ('SG', 'St. Gallen'), ('VS', 'Valais'), ('VD', 'Vaud'), ('ZH', 'Zurich'), ('VS-OW', 'Haut-Valais')], max_length=5, verbose_name="Canton d'affiliation"),
        ),
    ]
