# Generated by Django 3.2.13 on 2022-04-19 07:57
from django.contrib.auth import get_user_model

import apps.common.fields
from django.db import migrations, models


def forward(apps, schema_editor):
    """
    Reformat data for the new FieldType
    """
    User = get_user_model()
    for user in User.objects.all():
        user.profile.__setattr__(
            "languages_challenges",
            "{" + ",".join(user.profile.languages_challenges.split(",")) + "}"
        )
        user.profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0071_userprofile_activity_cantons'),
    ]

    operations = [
        migrations.RunPython(forward),
        migrations.AlterField(
            model_name='userprofile',
            name='languages_challenges',
            field=apps.common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('en', 'English')], max_length=2), blank=True, default=list, size=None, verbose_name='Prêt à animer en'),
        ),
    ]
