# Generated by Django 4.2.6 on 2023-10-10 09:27

import localflavor.generic.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0073_add_states_ow_nw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="iban",
            field=localflavor.generic.models.IBANField(
                blank=True,
                include_countries=(
                    "AD",
                    "AT",
                    "BE",
                    "BG",
                    "CH",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "EE",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GI",
                    "GR",
                    "HR",
                    "HU",
                    "IE",
                    "IS",
                    "IT",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MC",
                    "MT",
                    "NL",
                    "NO",
                    "PL",
                    "PT",
                    "RO",
                    "SE",
                    "SI",
                    "SK",
                    "SM",
                    "VA",
                ),
                max_length=34,
                use_nordea_extensions=False,
                verbose_name="Coordonnées bancaires (IBAN)",
            ),
        ),
    ]
