# Generated by Django 3.2.14 on 2023-12-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_add_states_ow_nw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='work_permit',
            new_name='work_permit_legacy',
        ),
    ]
