# Generated by Django 4.2.6 on 2024-06-17 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0074_alter_userprofile_iban"),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='work_permit',
            new_name='work_permit_legacy',
        ),
    ]
