# Generated by Django 4.2.6 on 2025-09-10 06:37

from django.db import migrations, models
import logging
import re

from django.conf import settings

logger = logging.getLogger(__name__)

UE_AELE = (
    "AT", "BE", "BG", "CH", "CY", "CZ", "DE", "DK", "ES", "EE", "FI", "FR", "GR", "HR",
    "HU", "IE", "IS", "IT", "LI", "LV", "LT", "LU", "MT", "NL", "NO", "PL", "PT", "RO",
    "SK", "SI", "SE"
)


def _legacy_to_new_workpermit(apps, schema_editor):
    UserProfile = apps.get_model("user", "UserProfile")
    profiles = UserProfile.objects.exclude(work_permit_legacy__isnull=True)
    for profile in profiles:
        legacy = profile.work_permit_legacy.lower()

        # New work permits dict by value
        new_work_permits = {
            v.lower(): k
            for k, v in dict(settings.WORK_PERMIT_CHOICES).items()
        }

        # Try to resolve legacy permit with regex
        match = re.match(pattern="^(permi[st] )?(ci|b|c|f|g|l|n|s).*$", string=legacy)
        if match:
            letter = match.groups()[1]

            if profile.nationality in UE_AELE:
                work_permit = new_work_permits["permis %s ue/aele" % letter]
            else:
                work_permit = new_work_permits["livret %s etat tiers" % letter]

            profile.work_permit = work_permit
            profile.save()
        else:
            if profile.work_permit_legacy != "":
                logger.warning(
                    "Profile %s with work permit legacy '%s' could not be "
                    "resolved to a new work permit.",
                    profile.pk,
                    profile.work_permit_legacy
                )


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0074_alter_userprofile_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '------'), (10, 'Femme'), (20, 'Homme'), (30, 'Non-binaire')], default=0, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_permit_legacy',
            field=models.CharField(blank=True, max_length=255, verbose_name='Permis de travail'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marital_status',
            field=models.PositiveSmallIntegerField(choices=[(0, '---------'), (10, 'Célibataire'), (20, 'Marié·e'), (30, 'Divorcé·e'), (40, 'Veu·f·ve'), (50, 'En partenariat enregistré'), (60, 'En partenariat dissous judiciairement'), (70, 'En partenariat dissous par décès'), (80, 'En partenariat dissous ensuite de déclaration d’absence')], default=0, verbose_name='État civil'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_permit',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (10, 'Permis B UE/AELE'), (20, 'Permis C UE/AELE'), (30, 'Permis Ci UE/AELE'), (40, 'Permis G UE/AELE'), (50, 'Permis L UE/AELE'), (60, 'Livret B Etat tiers'), (70, 'Livret C Etat tiers'), (80, 'Livret Ci Etat tiers'), (90, 'Livret F Etat tiers'), (100, 'Livret G Etat tiers'), (110, 'Livret L Etat tiers'), (120, 'Livret N Etat tiers'), (130, 'Livret S Etat tiers')], default=0, verbose_name='Permis de travail'),
        ),
    ]
