# Generated by Django 3.2.14 on 2023-12-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0074_rename_work_permit_to_work_permit_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='work_permit',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (10, 'Permis B UE/AELE'), (20, 'Permis C UE/AELE'), (30, 'Permis Ci UE/AELE'), (40, 'Permis G UE/AELE'), (50, 'Permis L UE/AELE'), (60, 'Livret B Etat tiers'), (70, 'Livret C Etat tiers'), (80, 'Livret Ci Etat tiers'), (90, 'Livret F Etat tiers'), (100, 'Livret G Etat tiers'), (110, 'Livret L Etat tiers'), (120, 'Livret N Etat tiers'), (130, 'Livret S Etat tiers')], default=0, verbose_name='Permis de travail'),
        ),
    ]
