# Generated by Django 4.2.6 on 2024-06-17 15:09
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0075_prepare_work_permit_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="work_permit",
            field=models.PositiveSmallIntegerField(
                choices=settings.WORK_PERMIT_CHOICES,
                default=0,
                verbose_name="Permis de travail",
            ),
        ),
    ]
