# Generated by Django 4.2.6 on 2025-09-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0075_prepare_work_permit_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '------'), (10, 'Femme'), (20, 'Homme'), (30, 'Non-binaire')], default=0, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_permit',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (10, 'Permis B UE/AELE'), (20, 'Permis C UE/AELE'), (30, 'Permis Ci UE/AELE'), (40, 'Permis G UE/AELE'), (50, 'Permis L UE/AELE'), (60, 'Livret B Etat tiers'), (70, 'Livret C Etat tiers'), (80, 'Livret Ci Etat tiers'), (90, 'Livret F Etat tiers'), (100, 'Livret G Etat tiers'), (110, 'Livret L Etat tiers'), (120, 'Livret N Etat tiers'), (130, 'Livret S Etat tiers')], default=0, verbose_name='Permis de travail'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marital_status',
            field=models.PositiveSmallIntegerField(choices=[(0, '---------'), (10, 'Célibataire'), (20, 'Marié·e'), (30, 'Divorcé·e'), (40, 'Veu·f·ve'), (50, 'En partenariat enregistré'), (60, 'En partenariat dissous judiciairement'), (70, 'En partenariat dissous par décès'), (80, 'En partenariat dissous ensuite de déclaration d’absence')], default=0, verbose_name='État civil'),
        ),
    ]
