# Generated by Django 4.2.6 on 2026-09-28 07:48

import apps.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0076_inclusive_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, choices=[('', '---------'), ('fr', 'Français'), ('de', 'Allemand'), ('it', 'Italien'), ('en', 'Anglais')], max_length=7, verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='languages_challenges',
            field=apps.common.fields.ChoiceArrayField(base_field=models.CharField(choices=[('fr', 'Français'), ('de', 'Allemand'), ('it', 'Italien'), ('en', 'Anglais')], max_length=2), blank=True, default=list, size=None, verbose_name='Prêt à animer en'),
        ),
    ]
