# Generated by Django 4.2.6 on 2025-09-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0076_userprofile_work_permit_legacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '------'), (10, 'Femme'), (20, 'Homme'), (30, 'Non-binaire')], default=0, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marital_status',
            field=models.PositiveSmallIntegerField(choices=[(0, '---------'), (10, 'Célibataire'), (20, 'Marié·e'), (30, 'Divorcé·e'), (40, 'Veu·f·ve'), (50, 'En partenariat enregistré'), (60, 'En partenariat dissous judiciairement'), (70, 'En partenariat dissous par décès'), (80, 'En partenariat dissous ensuite de déclaration d’absence')], default=0, verbose_name='État civil'),
        ),
    ]
