# Generated by Django 4.2.6 on 2024-06-17 15:16
import logging
import re

from django.conf import settings
from django.db import migrations

logger = logging.getLogger(__name__)

UE_AELE = (
    "AT", "BE", "BG", "CH", "CY", "CZ", "DE", "DK", "ES", "EE", "FI", "FR", "GR", "HR",
    "HU", "IE", "IS", "IT", "LI", "LV", "LT", "LU", "MT", "NL", "NO", "PL", "PT", "RO",
    "SK", "SI", "SE"
)


def _legacy_to_new_workpermit(apps, schema_editor):
    UserProfile = apps.get_model("user", "UserProfile")
    profiles = UserProfile.objects.exclude(work_permit_legacy__isnull=True)
    for profile in profiles:
        legacy = profile.work_permit_legacy.lower()

        # New work permits dict by value
        new_work_permits = {
            v.lower(): k
            for k, v in dict(settings.WORK_PERMIT_CHOICES).items()
        }

        # Try to resolve legacy permit with regex
        match = re.match(pattern="^(permis )?(ci|b|c|f|g|l|n|s).*$", string=legacy)
        if match:
            letter = match.groups()[1]

            if profile.nationality in UE_AELE:
                work_permit = new_work_permits["permis %s ue/aele" % letter]
            else:
                work_permit = new_work_permits["livret %s etat tiers" % letter]

            profile.work_permit = work_permit
            profile.save()
        else:
            if profile.work_permit_legacy != "":
                logger.warning(
                    "Profile %s with work permit legacy '%s' could not be "
                    "resolved to a new work permit.",
                    profile.pk,
                    profile.work_permit_legacy
                )


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0076_userprofile_work_permit_legacy_and_more"),
    ]

    operations = [
        migrations.RunPython(
            _legacy_to_new_workpermit,
            migrations.RunPython.noop
        )
    ]
