# Generated by Django 4.2.6 on 2024-06-17 15:17
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0077_migrate_workpermit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="marital_status",
            field=models.PositiveSmallIntegerField(
                choices=settings.MARITAL_STATUS_CHOICES,
                default=0,
                verbose_name="État civil",
            ),
        ),
    ]
