# Generated by Django 4.2.6 on 2025-09-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0078_update_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '------'), (10, 'Femme'), (20, 'Homme'), (30, 'Non-binaire')], default=0, verbose_name='Genre'),
        ),
    ]
