---
- hosts: all
  vars_files:
   - parameters.yml
  become: no

  roles:
    - { role: base }
    - { role: git }
    - { role: postgresql }
    - { role: python }

  tasks:
    - name: install postgresql-contrib
      apt: pkg=postgresql-contrib state=latest
      become: yes
    - name: Allow password-less connection to the postgres user (mimics Travis-CI)
      template: src=templates/pg_hba.conf.j2 dest=/etc/postgresql/11/main/pg_hba.conf
      become: yes
    - name: ensure postgresql is restarted
      action: service name=postgresql state=restarted
      become: yes
    - name: create venv and install base packages
      pip:
        virtualenv: "~/venv"
        virtualenv_command: pyvenv
        name: "{{ item }}"
      with_items:
        - pip==19.0.2
        - tox==3.14.2