---
- hosts: all
  vars_files:
   - parameters.yml
  become: no

  roles:
    - { role: base }
    - { role: git }
    - { role: postgresql }
    - { role: django }
    - { role: gitlabci }

  tasks:
    - name: install postgresql-contrib
      apt: pkg=postgresql-contrib state=latest
      become: yes
    - name: Allow password-less connection to the postgres user (mimics Travis-CI)
      template: src=templates/pg_hba.conf.j2 dest=/etc/postgresql/11/main/pg_hba.conf
      become: yes
    - name: ensure postgresql is restarted
      action: service name=postgresql state=restarted
      become: yes
