# Generated by Django 4.2.6 on 2024-06-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0009_add_address_ofs_no_and_address_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_zip",
            field=models.CharField(blank=True, max_length=10, verbose_name="NPA"),
        ),
    ]
