# Generated by Django 2.2.12 on 2020-05-18 12:28

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0008_monthlycantonalvalidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCantonalValidationUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'URL pour validation mensuelle',
                'verbose_name_plural': 'URLs pour validation mensuelle',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MonthlyCantonalValidationUrlTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='salary.MonthlyCantonalValidationUrl')),
            ],
            options={
                'verbose_name': 'URL pour validation mensuelle Translation',
                'db_table': 'salary_monthlycantonalvalidationurl_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
