# Generated by Django 3.2.14 on 2023-09-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0017_monthlycantonalvalidationurltranslation_url_translate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycantonalvalidation',
            name='canton',
            field=models.CharField(choices=[('AG', 'Aargau'), ('AR', 'Appenzell Ausserrhoden'), ('BS', 'Basel-Stadt'), ('BL', 'Basel-Land'), ('BE', 'Berne'), ('FR', 'Fribourg'), ('GE', 'Geneva'), ('GR', 'Graubuenden'), ('JU', 'Jura'), ('LU', 'Lucerne'), ('NE', 'Neuchatel'), ('NW', 'Nidwalden'), ('OW', 'Obwalden'), ('SZ', 'Schwyz'), ('SO', 'Solothurn'), ('SG', 'St. Gallen'), ('VS', 'Valais'), ('VD', 'Vaud'), ('ZG', 'Zug'), ('ZH', 'Zurich')], max_length=2, unique_for_month='date', unique_for_year='date', verbose_name='Canton'),
        ),
    ]
