# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0044_season_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['year', '-season', 'cantons'], 'verbose_name': 'Saison', 'verbose_name_plural': 'Saisons'},
        ),
        migrations.AddField(
            model_name='session',
            name='bikes_concept',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='session',
            name='bikes_phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
