# Generated by Django 2.2.9 on 2020-04-08 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0060_alter_invoiceline_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceline",
            name="historical_session",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="challenge.HistoricalSession",
            ),
            preserve_default=False,
        ),
    ]
