# Generated by Django 2.2.16 on 2020-12-09 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0076_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='classes_amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Nb de classes (1 à 6)'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='day_time',
            field=models.IntegerField(choices=[(0, 'Matin'), (1, 'Après-midi')], default=0),
        ),
    ]
