# Generated by Django 2.2.24 on 2022-01-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenge", "0078_auto_20210111_1054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalseason",
            name="cantons",
            field=models.CharField(
                choices=[
                    ("AG", "Aargau"),
                    ("AR", "Appenzell Ausserrhoden"),
                    ("BE", "Berne"),
                    ("BL", "Basel-Land"),
                    ("BS", "Basel-Stadt"),
                    ("FR", "Fribourg"),
                    ("GE", "Geneva"),
                    ("GR", "Graubuenden"),
                    ("JU", "Jura"),
                    ("LU", "Lucerne"),
                    ("NE", "Neuchatel"),
                    ("SG", "St. Gallen"),
                    ("SO", "Solothurn"),
                    ("SZ", "Schwyz"),
                    ("VD", "Vaud"),
                    ("VS", "Valais"),
                    ("ZG", "Zug"),
                    ("ZH", "Zurich"),
                ],
                max_length=53,
                verbose_name="Cantons",
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="cantons",
            field=models.CharField(
                choices=[
                    ("AG", "Aargau"),
                    ("AR", "Appenzell Ausserrhoden"),
                    ("BE", "Berne"),
                    ("BL", "Basel-Land"),
                    ("BS", "Basel-Stadt"),
                    ("FR", "Fribourg"),
                    ("GE", "Geneva"),
                    ("GR", "Graubuenden"),
                    ("JU", "Jura"),
                    ("LU", "Lucerne"),
                    ("NE", "Neuchatel"),
                    ("SG", "St. Gallen"),
                    ("SO", "Solothurn"),
                    ("SZ", "Schwyz"),
                    ("VD", "Vaud"),
                    ("VS", "Valais"),
                    ("ZG", "Zug"),
                    ("ZH", "Zurich"),
                ],
                max_length=53,
                verbose_name="Cantons",
            ),
        ),
    ]
