# Generated by Django 3.2.14 on 2023-09-05 08:02

from django.db import migrations, models

import apps.common.fields


class Migration(migrations.Migration):
    dependencies = [
        ("challenge", "0081_auto_20220714_1306"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalseason",
            name="cantons",
            field=apps.common.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("AG", "Aargau"),
                        ("AR", "Appenzell Ausserrhoden"),
                        ("BE", "Berne"),
                        ("BL", "Basel-Land"),
                        ("BS", "Basel-Stadt"),
                        ("FR", "Fribourg"),
                        ("GE", "Geneva"),
                        ("GR", "Graubuenden"),
                        ("JU", "Jura"),
                        ("LU", "Lucerne"),
                        ("NE", "Neuchatel"),
                        ("NW", "Nidwalden"),
                        ("OW", "Obwalden"),
                        ("SG", "St. Gallen"),
                        ("SO", "Solothurn"),
                        ("SZ", "Schwyz"),
                        ("VD", "Vaud"),
                        ("VS", "Valais"),
                        ("ZG", "Zug"),
                        ("ZH", "Zurich"),
                    ],
                    max_length=2,
                ),
                default=list,
                size=None,
                verbose_name="Cantons",
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="cantons",
            field=apps.common.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("AG", "Aargau"),
                        ("AR", "Appenzell Ausserrhoden"),
                        ("BE", "Berne"),
                        ("BL", "Basel-Land"),
                        ("BS", "Basel-Stadt"),
                        ("FR", "Fribourg"),
                        ("GE", "Geneva"),
                        ("GR", "Graubuenden"),
                        ("JU", "Jura"),
                        ("LU", "Lucerne"),
                        ("NE", "Neuchatel"),
                        ("NW", "Nidwalden"),
                        ("OW", "Obwalden"),
                        ("SG", "St. Gallen"),
                        ("SO", "Solothurn"),
                        ("SZ", "Schwyz"),
                        ("VD", "Vaud"),
                        ("VS", "Valais"),
                        ("ZG", "Zug"),
                        ("ZH", "Zurich"),
                    ],
                    max_length=2,
                ),
                default=list,
                size=None,
                verbose_name="Cantons",
            ),
        ),
    ]
