# Generated by Django 4.2.6 on 2024-06-17 15:09

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("challenge", "0082_add_states_ow_nw"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsession",
            name="address_country",
            field=django_countries.fields.CountryField(
                default="CH", max_length=2, verbose_name="Pays"
            ),
        ),
        migrations.AddField(
            model_name="historicalsession",
            name="address_ofs_no",
            field=models.CharField(
                blank=True, max_length=4, verbose_name="Commune OFS"
            ),
        ),
    ]
