# Generated by Django 4.2.6 on 2025-09-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0083_historicalsession_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsession',
            name='address_zip',
            field=models.CharField(blank=True, max_length=10, verbose_name='NPA'),
        ),
    ]
