# Generated by Django 4.2.6 on 2025-09-10 06:37

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0088_alter_historicalqualification_n_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsession',
            name='address_country',
            field=django_countries.fields.CountryField(default='CH', max_length=2, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='historicalsession',
            name='address_ofs_no',
            field=models.CharField(blank=True, max_length=4, verbose_name='Commune OFS'),
        ),
        migrations.AlterField(
            model_name='historicalsession',
            name='address_zip',
            field=models.CharField(blank=True, max_length=10, verbose_name='NPA'),
        ),
    ]
