# Generated by Django 4.2.6 on 2026-09-28 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_squashed_0002_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modifié'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
    ]
