AVAILABILITY_FIELDKEY_HELPER_PREFIX = 'avail-h{hpk}-'
STAFF_FIELDKEY_HELPER_PREFIX = 'staff-h{hpk}-'

AVAILABILITY_FIELDKEY = AVAILABILITY_FIELDKEY_HELPER_PREFIX + 's{spk}'
STAFF_FIELDKEY = STAFF_FIELDKEY_HELPER_PREFIX + 's{spk}'